config/routes.rb
Bbq::Application.routes.draw do
  resources :quotes do
    member do
      post 'upvote'
      post 'downvote'
    end
    
    collection do
      get 'recent'
      get 'top'
      get 'bottom'
      get 'random'
      get 'search'
    end
  end
  
  resources :tags

  root to: 'welcome#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  class << self
    def recent num = 20
      order("created_at DESC").take(num)
    end
    
    def top num = 20
      order("score DESC").take(num)
    end
    
    def bottom num=20
      order(:score).take(num)
    end
    
    def random num=20
      order("random()").take(num)
    end
    
    def search query
      if query
        Quote.where "text like ?", "%#{query}%"
      else
        Quote.all
      end
    end
  end
  
  has_and_belongs_to_many :tags
  attr_accessible :text, :context, :score, :tag_tokens
  
  def tag_tokens
    if self.tag_ids.length > 0
      self.tag_ids.join(',')
    else
      '[]'
    end
  end
  
  def tag_tokens=(ids)
    self.tag_ids = ids.split(',')
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :quotes
  
  def num_quotes
    return quotes.length
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	before_filter :find_quote, except: [:index]
	before_filter :find_quotes, only: [:index]

	respond_to :html, :json

	def index
	end
	
	def recent
		@quotes = Quote.recent
	end
	
	def top
		@quotes = Quote.top
	end
	
	def bottom
		@quotes = Quote.bottom
	end
	
	def random
		@quotes = Quote.random
	end
	
	def search
		@search_string = params[:quote][:text]
		@quotes = Quote.search(@search_string)
	end

	def new
	end

	def edit
	end

	def show
	end

	def destroy
		@quote.destroy

		respond_to do |format|
			format.html { redirect_to quotes_path, notice: 'Quote deleted' }
			format.json { head :ok }
		end
	end

	def create
		respond_to do |format|
			if @quote.save
				format.html { redirect_to quotes_path, notice: 'Quote submitted' }
				format.json { render json: @quote, status: :created, location: @quote }
			else
				format.html { render action: new }
				format.json { render json: @quote.errors, status: :unprocessable_entity }
			end
		end
	end

	def update
		respond_to do |format|
			if @quote.update_attributes params[:quote]
				format.html { redirect_to quote_path(@quote), notice: 'Quote updated' }
				format.json { head :ok }
			else
				format.html { render action: edit }
				format.json { render json: @quote.errors, status: :unprocessable_entity }
			end
		end
	end

	def upvote
		@quote.score += 1

		respond_to do |format|
			if @quote.save
				format.html { redirect_to quote_path(@quote)}
				format.json { head :ok }
			else
				format.html { redirect_to quote_path(@quote), notice: 'Failed to upvote this quote'}
				format.json { render json: @quote.errors, status: :unprocessable_entity }
			end
		end
	end

	def downvote
		@quote.score -= 1

		respond_to do |format|
			if @quote.save
				format.html { redirect_to quote_path(@quote)}
				format.json { head :ok }
			else
				format.html { redirect_to quote_path(@quote), notice: 'Failed to downvote this quote'}
				format.json { render json: @quote.errors, status: :unprocessable_entity }
			end
		end
	end		

	private
	def find_quotes
		@quotes = Quote.all
	end

	def find_quote
		@quote = Quote.find(params[:id]) if params[:id]
		@quote ||= Quote.new(params[:quote]) if params[:quote]
		@quote ||= Quote.new
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :find_tags, only: [:index]
  before_filter :find_tag, except: [:index]
  
  helper :tag_cloud
  
  respond_to :html, :json
  
  def index
    respond_to do |format|
      format.html 
      format.json { render json: @tags }
    end
  end
  
  def new
  end
  
  def create
    respond_to do |format|
      if @tag.save
        format.html { redirect_to tags_path, notice: 'Quote submitted' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
    respond_with @tag
  end
  
  protected
  def find_tags
    @tags = Tag.where("name like ?", "%#{params[:q]}%")
    @tags ||= Tag.all
  end
  
  def find_tag
    @tag = Tag.find(params[:id]) if params[:id]
    @tag ||= Tag.new(params[:tag]) if params[:tag]
    @tag ||= Tag.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tag_cloud_helper.rb
module TagCloudHelper
  
  def tag_cloud_for collection, sort_method, display_property
    sorted = collection.sort_by(&sort_method).reverse
    
    scores = score_array sorted
    
    collection.map do |tag|
      tag_output_for(tag, scores[tag.id], display_property)
    end.join(" ")
  end
  
  def tag_output_for tag, score, display_property
    link_to tag.send(display_property), tag, class: "tag-cloud-#{score+1}"
  end
  
  def score_array sorted_array
    chunks = chunk_array sorted_array, 6
    
    scores = {}
    
    chunks.each_with_index do |chunk, score|
      chunk.each do |tag|
        scores[tag.id] = score
      end
    end
    
    scores
  end
  
  def chunk_array array, num_chunks
    width = (array.length / num_chunks) + 1
    
    array.each_slice(width).to_a
  end
end

app/views/layouts/application.haml
!!! 5
%html
	%head
		%title Big Bad Quotes
		= stylesheet_link_tag "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body
		.navbar
			.navbar-inner
				.container
					= link_to "Big Bad Quotes", '/', class: "brand"
					.nav-collapse
						%ul.nav
							%li
								= link_to "Recent", recent_quotes_path
							%li
								= link_to "Top", top_quotes_path
							%li
								= link_to "Bottom", bottom_quotes_path
							%li
								= link_to "Browse", quotes_path
							%li
								= link_to "Random", random_quotes_path
							%li
								= link_to "Tags", tags_path
							%li
								= link_to "Submit Quote", new_quote_path
						= form_tag search_quotes_path, method: :get, class: ["navbar-search", "pull-left"], id: "search-form" do
							= search_field :quote, :text, id: "search", class: ["search-query", "span2"]
							= submit_tag "search", class: "hidden", id: "search-submit"
		.container
			- if flash[:error]
				.alert.alert-error
					= flash[:error]
			- if flash[:notice]
				.alert.alert-success
					= flash[:notice]
			= yield

app/views/quotes/_form.haml
= simple_form_for quote  do |f|
	= f.error_notification
	
	= f.input :text, as: :text, id: 'quote', input_html: { class: 'span12', rows: 5 }
	= f.input :context, input_html: { class: 'span12' }
	= f.input :tag_tokens, id: 'quote_tags', input_html: {class: 'span12'}, "data-pre" => quote.tags.map(&:attributes).to_json, label: 'Tags'

	.form-actions
		= f.button :submit, action, class: 'btn-primary'

app/views/quotes/bottom.haml
%h2 Bottom Quotes

= render :partial => "quote", :collection => @quotes

app/views/quotes/edit.haml
.page-header
	%h2 
		= "Edit Quote ##{@quote.id}"
= render partial: 'form', locals: { quote: @quote, action: 'Save Quote' }

app/views/quotes/index.haml
%h2 All Quotes

= render :partial => "quote", :collection => @quotes

app/views/quotes/new.haml
.page-header
	%h2 Create a Quote
= render partial: 'form', locals: { quote: @quote, action: 'Submit Quote' }

app/views/quotes/random.haml
%h2 Random Quotes

= render :partial => "quote", :collection => @quotes

app/views/quotes/recent.haml
%h2 Recent Quotes

= render :partial => "quote", :collection => @quotes

app/views/quotes/search.haml
%h1 
  = "Search Results for #{@search_string}"

- if @quotes.empty?
  Sorry, no search results...
- else
  = render :partial => "quote", :collection => @quotes

app/views/quotes/show.haml
= render partial: 'quote', object: @quote

= link_to "Edit this quote", edit_quote_path(@quote)
= link_to 'Delete quote', @quote, method: :delete, confirm: "Are you sure you want to delete this quote?"

app/views/quotes/top.haml
%h2 Top Quotes

= render :partial => "quote", :collection => @quotes

app/views/shared/_quote.haml
.page-header
	%h2 
		= link_to "Quote ##{quote.id}", quote
.row
	.score-container.span1
		.upvote
			= link_to image_tag("upvote-inactive.png", alt: 'upvote'), upvote_quote_path, method: :post
		.score
			= quote.score
		.downvote
			= link_to image_tag("downvote-inactive.png", alt: 'downvote'), downvote_quote_path, method: :post
	.quote-container.span11
		.quote-text
			- quote.text.each_line do |line|
				= line
				%br
		- if quote.context && quote.context.length > 0
			.quote-context
				= quote.context
		- unless quote.tags.empty?
			.quote-tags
				= quote.tags.map(&:name).join(" ")

app/views/shared/_tag.haml
%span
  = tag.name

app/views/tags/_form.haml
= simple_form_for tag do |f|
  = f.error_notification
  
  = f.input :name, input_html: { class: 'span12' }
  
  .form-actions
    = f.button :submit, action, class: 'btn-primary'

app/views/tags/index.haml
%h1 Tags

= raw tag_cloud_for @tags, :num_quotes, :name

app/views/tags/new.haml
.page-header
  %h2 Create a Tag
= render partial: 'form', locals: { tag: @tag, action: 'Create Tag' }

app/views/tags/show.haml
= "Quotes tagged with \"#{@tag.name}\""

= render :partial => "shared/quote", :collection => @tag.quotes

app/views/welcome/index.html.haml
%h2 Welcome to Big Bad Quotes
%p This is the quote managment system for [Insert Organization Here]. Enjoy!